import:
  - docker/keycloak.yml

services:
  book_service:
    build:
      context: ./services/book-service
    ports:
      - "3001:3001"
    env_file: ".env"

  lending_service:
    build:
      context: ./services/lending-service
    ports:
      - "3000:3000"
    env_file: ".env"

  user_service:
    build:
      context: ./services/user-service
    ports:
      - "3002:3002"
    env_file: ".env"
