services:
  book_service:
    build:
      context: ./services/book-service
    ports:
      - "3001:3001"
    env_file: ".env"

  lending_service:
    build:
      context: ./services/lending-service
    ports:
      - "3000:3000"
    env_file: ".env"

  notification_service:
    build:
      context: ./services/lending-service
    ports:
      - "3003:3003"
    env_file: ".env"

  user_service:
    build:
      context: ./services/user-service
    ports:
      - "3002:3002"
    env_file: ".env"

  gateway:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    depends_on:
      - user_service
      - book_service
      - notification_service
      - lending_service
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf:z
    restart: unless-stopped
