events {}

http {
    upstream lending_service {
        server ${LENDING_SERVICE_URL};
    }

    upstream book_service {
        server ${BOOK_SERVICE_URL};
    }

    upstream user_service {
        server ${USER_SERVICE_URL};
    }

    upstream notification_service {
        server ${NOTIFICATION_SERVICE_URL};
    }

    server {
        listen 80;

        location = /_internal/validate_token {
          internal;

          proxy_pass              https://user_service/api/auth/validate;
          proxy_pass_request_body off;
          proxy_set_header        Content-Length   "";
          proxy_set_header        X-Original-URI   $request_uri;
          proxy_set_header        X-Original-Method $request_method;
          proxy_set_header Host ${USER_SERVICE_URL};
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_set_header        Authorization   $http_authorization;
        }

        location /api/auth/ {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host ${USER_SERVICE_URL};
          proxy_pass https://user_service/api/auth/ ;
        }

        #  Protected

        location /api/users/ {
          auth_request /_internal/validate_token;

          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host ${USER_SERVICE_URL};
          proxy_pass https://user_service;

          error_page 401 = @unauthorized;
          error_page 403 = @forbidden;
        }


        location /api/books/ {
          auth_request /_internal/validate_token;

          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host ${BOOK_SERVICE_URL};
          proxy_pass https://book_service;

          error_page 401 = @unauthorized;
          error_page 403 = @forbidden;
        }

         location /api/notification/ {
          auth_request /_internal/validate_token;

          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host ${NOTIFICATION_SERVICE_URL};
          proxy_pass https://notification_service;

          error_page 401 = @unauthorized;
          error_page 403 = @forbidden;
        }

        location /api/lendings/ {
          auth_request /_internal/validate_token;

          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host ${LENDING_SERVICE_URL};
          proxy_pass https://lending_service;

          error_page 401 = @unauthorized;
          error_page 403 = @forbidden;
        }

        location @unauthorized {
          default_type application/json;
          return 401 '{"error":"Unauthorized","message":"A valid Bearer token is required."}';
        }

        location @forbidden {
          default_type application/json;
          return 403 '{"error":"Forbidden","message":"You do not have permission to access this resource."}';
        }


    }
}
