name: Trigger auto deployment for ca-book-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "services/book-service/**"
      - ".github/workflows/ca-book-service-AutoDeployTrigger-5f850990-2b12-43bf-aa03-d168bfadeb33.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CABOOKSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CABOOKSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CABOOKSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/service/book-service
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ctselibrarymanagement.azurecr.io
          registryUsername: ${{ secrets.CABOOKSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CABOOKSERVICE_REGISTRY_PASSWORD }}
          containerAppName: ca-book-service
          resourceGroup: rg-ctse-library-management
          imageToBuild: ctselibrarymanagement.azurecr.io/ca-book-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
