name: Frontend Node CI

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
       
        with:
          node-version: 22.x

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          cache: true
          package_json_file: ./package.json
          cache_dependency_path: ./frontend/pnpm-lock.yaml
          version: 10
          run_install: |
            - recursive: true

      - run: pnpm lint
        working-directory: ./frontend

      - run: pnpm test
        working-directory: ./frontend
